<?php

declare(strict_types=1);

/**
 * @package   Akeneo\Connector\view\adminhtml\templates\jobgrid
 * @author    Agence Dn'D <contact@dnd.fr>
 * @copyright 2004-present Agence Dn'D
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link      https://www.dnd.fr/
 */
use Akeneo\Connector\ViewModel\Jobgrid\AutoReloadConfig;
use Magento\Framework\View\Element\Template;

/** @var AutoReloadConfig $viewModel
 * @var Template $block
 */
$viewModel = $block->getAkeneoConnectorJobgridAutoreloadconfigViewModel();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Akeneo_Connector/js/autoReload": {
                "autoReloadEnabled": "<?= $viewModel->isAutoReloadEnabled() ?>",
                "watchableStatusIds": "<?= $viewModel->getWatchableStatusIds() ?>"
            }
        }
    }
</script>
